
CREATE TABLE COMPRADOR (
  ID bigint(6) NOT NULL AUTO_INCREMENT,
  NOME varchar(50) DEFAULT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE COMERCIANTE (
  ID bigint(6) NOT NULL AUTO_INCREMENT,
  NOME varchar(50) DEFAULT NULL,
  ENDERECO varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PRODUTO (
  ID bigint(6) NOT NULL AUTO_INCREMENT,
  DESCRICAO varchar(50) DEFAULT NULL,
  PRECO decimal(6,2) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PEDIDO (
  ID bigint(6) NOT NULL AUTO_INCREMENT,
  COMPRADOR_ID bigint(6) NOT NULL,
  COMERCIANTE_ID bigint(6) NOT NULL,
  PRODUTO_ID bigint(6) NOT NULL,
  QUANTIDADE bigint(6) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK859n2jvi8ivhui0rl0esws6o FOREIGN KEY (COMPRADOR_ID) REFERENCES COMPRADOR (ID),
  CONSTRAINT FKa68196081fvovjhkek5m97n3 FOREIGN KEY (COMERCIANTE_ID) REFERENCES COMERCIANTE (ID),
  CONSTRAINT FKa68196081ivhui0rl0esws6o FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID)
);
